pipeline {
    agent {
        node {
            label 'terraform-runner'
            customWorkspace '/home/ankit/git/Azure Secret Management Via Jenkins'
        }
    }

    stages {
        stage('Vault Secret Retrieval') {
            steps {
                withVault(configuration: [
                              vaultUrl: 'http://127.0.0.1:8200',
                              vaultCredentialId: 'vault-approle-id' 
                          ],
                          vaultSecrets: [[
                              path: 'internal/azure-creds', 
                              engineVersion: 2, 
                              secretValues: [
                                  [envVar: 'ARM_CLIENT_ID', vaultKey: 'client_id'],
                                  [envVar: 'ARM_CLIENT_SECRET', vaultKey: 'client_secret'],
                                  [envVar: 'ARM_SUBSCRIPTION_ID', vaultKey: 'subscription_id'],
                                  [envVar: 'ARM_TENANT_ID', vaultKey: 'tenant_id']
                              ]
                          ]]) {
                    sh 'echo "Vault Secrets successfully injected."'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                // Pointing to the absolute path on NTZ-LINUX-003
                dir('/home/ankit/git/Azure Secret Management Via Jenkins/terraform') { 
                    sh 'terraform init'
                    sh 'terraform plan'
                }
            }
        }
    }
}